// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat_proto/chat.proto

package io.grpc.chatservice;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatservice.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string clientKey = 1;</code>
   */
  java.lang.String getClientKey();
  /**
   * <code>optional string clientKey = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientKeyBytes();

  /**
   * <code>optional string nick = 2;</code>
   */
  java.lang.String getNick();
  /**
   * <code>optional string nick = 2;</code>
   */
  com.google.protobuf.ByteString
      getNickBytes();
}
