// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoExercise/chat_proto/chat.proto

package main.java.io.grpc.chatservice;

/**
 * Protobuf type {@code chatservice.RetVal}
 */
public  final class RetVal extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:chatservice.RetVal)
    RetValOrBuilder {
  // Use RetVal.newBuilder() to construct.
  private RetVal(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RetVal() {
    retval_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private RetVal(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            retval_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return main.java.io.grpc.chatservice.ChatServiceProto.internal_static_chatservice_RetVal_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return main.java.io.grpc.chatservice.ChatServiceProto.internal_static_chatservice_RetVal_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            main.java.io.grpc.chatservice.RetVal.class, main.java.io.grpc.chatservice.RetVal.Builder.class);
  }

  public static final int RETVAL_FIELD_NUMBER = 1;
  private volatile java.lang.Object retval_;
  /**
   * <code>optional string retval = 1;</code>
   */
  public java.lang.String getRetval() {
    java.lang.Object ref = retval_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      retval_ = s;
      return s;
    }
  }
  /**
   * <code>optional string retval = 1;</code>
   */
  public com.google.protobuf.ByteString
      getRetvalBytes() {
    java.lang.Object ref = retval_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      retval_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRetvalBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, retval_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRetvalBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, retval_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static main.java.io.grpc.chatservice.RetVal parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.java.io.grpc.chatservice.RetVal parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.java.io.grpc.chatservice.RetVal parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.java.io.grpc.chatservice.RetVal parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.java.io.grpc.chatservice.RetVal parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static main.java.io.grpc.chatservice.RetVal parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static main.java.io.grpc.chatservice.RetVal parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static main.java.io.grpc.chatservice.RetVal parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static main.java.io.grpc.chatservice.RetVal parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static main.java.io.grpc.chatservice.RetVal parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(main.java.io.grpc.chatservice.RetVal prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chatservice.RetVal}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chatservice.RetVal)
      main.java.io.grpc.chatservice.RetValOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return main.java.io.grpc.chatservice.ChatServiceProto.internal_static_chatservice_RetVal_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return main.java.io.grpc.chatservice.ChatServiceProto.internal_static_chatservice_RetVal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              main.java.io.grpc.chatservice.RetVal.class, main.java.io.grpc.chatservice.RetVal.Builder.class);
    }

    // Construct using main.java.io.grpc.chatservice.RetVal.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      retval_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return main.java.io.grpc.chatservice.ChatServiceProto.internal_static_chatservice_RetVal_descriptor;
    }

    public main.java.io.grpc.chatservice.RetVal getDefaultInstanceForType() {
      return main.java.io.grpc.chatservice.RetVal.getDefaultInstance();
    }

    public main.java.io.grpc.chatservice.RetVal build() {
      main.java.io.grpc.chatservice.RetVal result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public main.java.io.grpc.chatservice.RetVal buildPartial() {
      main.java.io.grpc.chatservice.RetVal result = new main.java.io.grpc.chatservice.RetVal(this);
      result.retval_ = retval_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof main.java.io.grpc.chatservice.RetVal) {
        return mergeFrom((main.java.io.grpc.chatservice.RetVal)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(main.java.io.grpc.chatservice.RetVal other) {
      if (other == main.java.io.grpc.chatservice.RetVal.getDefaultInstance()) return this;
      if (!other.getRetval().isEmpty()) {
        retval_ = other.retval_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      main.java.io.grpc.chatservice.RetVal parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (main.java.io.grpc.chatservice.RetVal) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object retval_ = "";
    /**
     * <code>optional string retval = 1;</code>
     */
    public java.lang.String getRetval() {
      java.lang.Object ref = retval_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        retval_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string retval = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRetvalBytes() {
      java.lang.Object ref = retval_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retval_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string retval = 1;</code>
     */
    public Builder setRetval(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      retval_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string retval = 1;</code>
     */
    public Builder clearRetval() {
      
      retval_ = getDefaultInstance().getRetval();
      onChanged();
      return this;
    }
    /**
     * <code>optional string retval = 1;</code>
     */
    public Builder setRetvalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      retval_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:chatservice.RetVal)
  }

  // @@protoc_insertion_point(class_scope:chatservice.RetVal)
  private static final main.java.io.grpc.chatservice.RetVal DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new main.java.io.grpc.chatservice.RetVal();
  }

  public static main.java.io.grpc.chatservice.RetVal getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RetVal>
      PARSER = new com.google.protobuf.AbstractParser<RetVal>() {
    public RetVal parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new RetVal(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<RetVal> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RetVal> getParserForType() {
    return PARSER;
  }

  public main.java.io.grpc.chatservice.RetVal getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

