// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoExercise/chat_proto/chat.proto

package main.java.io.grpc.chatservice;

public interface RetValOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatservice.RetVal)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string retval = 1;</code>
   */
  java.lang.String getRetval();
  /**
   * <code>optional string retval = 1;</code>
   */
  com.google.protobuf.ByteString
      getRetvalBytes();
}
