// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat_proto/chat.proto

package io.grpc.chatservice;

public interface ChannelUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatservice.ChannelUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string channelName = 1;</code>
   */
  java.lang.String getChannelName();
  /**
   * <code>optional string channelName = 1;</code>
   */
  com.google.protobuf.ByteString
      getChannelNameBytes();

  /**
   * <code>optional string clientKey = 2;</code>
   */
  java.lang.String getClientKey();
  /**
   * <code>optional string clientKey = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientKeyBytes();
}
