// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoExercise/chat_proto/chat.proto

package main.java.io.grpc.chatservice;

/**
 * Protobuf type {@code chatservice.Channel}
 */
public  final class Channel extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:chatservice.Channel)
    ChannelOrBuilder {
  // Use Channel.newBuilder() to construct.
  private Channel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Channel() {
    channelName_ = "";
    users_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Channel(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            channelName_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              users_ = new java.util.ArrayList<main.java.io.grpc.chatservice.User>();
              mutable_bitField0_ |= 0x00000002;
            }
            users_.add(input.readMessage(main.java.io.grpc.chatservice.User.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw new RuntimeException(e.setUnfinishedMessage(this));
    } catch (java.io.IOException e) {
      throw new RuntimeException(
          new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this));
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        users_ = java.util.Collections.unmodifiableList(users_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return main.java.io.grpc.chatservice.ChatServiceProto.internal_static_chatservice_Channel_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return main.java.io.grpc.chatservice.ChatServiceProto.internal_static_chatservice_Channel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            main.java.io.grpc.chatservice.Channel.class, main.java.io.grpc.chatservice.Channel.Builder.class);
  }

  private int bitField0_;
  public static final int CHANNELNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object channelName_;
  /**
   * <code>optional string channelName = 1;</code>
   */
  public java.lang.String getChannelName() {
    java.lang.Object ref = channelName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      channelName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string channelName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getChannelNameBytes() {
    java.lang.Object ref = channelName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      channelName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERS_FIELD_NUMBER = 2;
  private java.util.List<main.java.io.grpc.chatservice.User> users_;
  /**
   * <code>repeated .chatservice.User users = 2;</code>
   */
  public java.util.List<main.java.io.grpc.chatservice.User> getUsersList() {
    return users_;
  }
  /**
   * <code>repeated .chatservice.User users = 2;</code>
   */
  public java.util.List<? extends main.java.io.grpc.chatservice.UserOrBuilder> 
      getUsersOrBuilderList() {
    return users_;
  }
  /**
   * <code>repeated .chatservice.User users = 2;</code>
   */
  public int getUsersCount() {
    return users_.size();
  }
  /**
   * <code>repeated .chatservice.User users = 2;</code>
   */
  public main.java.io.grpc.chatservice.User getUsers(int index) {
    return users_.get(index);
  }
  /**
   * <code>repeated .chatservice.User users = 2;</code>
   */
  public main.java.io.grpc.chatservice.UserOrBuilder getUsersOrBuilder(
      int index) {
    return users_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getChannelNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, channelName_);
    }
    for (int i = 0; i < users_.size(); i++) {
      output.writeMessage(2, users_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getChannelNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, channelName_);
    }
    for (int i = 0; i < users_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, users_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  public static main.java.io.grpc.chatservice.Channel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.java.io.grpc.chatservice.Channel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.java.io.grpc.chatservice.Channel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static main.java.io.grpc.chatservice.Channel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static main.java.io.grpc.chatservice.Channel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static main.java.io.grpc.chatservice.Channel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static main.java.io.grpc.chatservice.Channel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static main.java.io.grpc.chatservice.Channel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static main.java.io.grpc.chatservice.Channel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static main.java.io.grpc.chatservice.Channel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(main.java.io.grpc.chatservice.Channel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chatservice.Channel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chatservice.Channel)
      main.java.io.grpc.chatservice.ChannelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return main.java.io.grpc.chatservice.ChatServiceProto.internal_static_chatservice_Channel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return main.java.io.grpc.chatservice.ChatServiceProto.internal_static_chatservice_Channel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              main.java.io.grpc.chatservice.Channel.class, main.java.io.grpc.chatservice.Channel.Builder.class);
    }

    // Construct using main.java.io.grpc.chatservice.Channel.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getUsersFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      channelName_ = "";

      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        usersBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return main.java.io.grpc.chatservice.ChatServiceProto.internal_static_chatservice_Channel_descriptor;
    }

    public main.java.io.grpc.chatservice.Channel getDefaultInstanceForType() {
      return main.java.io.grpc.chatservice.Channel.getDefaultInstance();
    }

    public main.java.io.grpc.chatservice.Channel build() {
      main.java.io.grpc.chatservice.Channel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public main.java.io.grpc.chatservice.Channel buildPartial() {
      main.java.io.grpc.chatservice.Channel result = new main.java.io.grpc.chatservice.Channel(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.channelName_ = channelName_;
      if (usersBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          users_ = java.util.Collections.unmodifiableList(users_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.users_ = users_;
      } else {
        result.users_ = usersBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof main.java.io.grpc.chatservice.Channel) {
        return mergeFrom((main.java.io.grpc.chatservice.Channel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(main.java.io.grpc.chatservice.Channel other) {
      if (other == main.java.io.grpc.chatservice.Channel.getDefaultInstance()) return this;
      if (!other.getChannelName().isEmpty()) {
        channelName_ = other.channelName_;
        onChanged();
      }
      if (usersBuilder_ == null) {
        if (!other.users_.isEmpty()) {
          if (users_.isEmpty()) {
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUsersIsMutable();
            users_.addAll(other.users_);
          }
          onChanged();
        }
      } else {
        if (!other.users_.isEmpty()) {
          if (usersBuilder_.isEmpty()) {
            usersBuilder_.dispose();
            usersBuilder_ = null;
            users_ = other.users_;
            bitField0_ = (bitField0_ & ~0x00000002);
            usersBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getUsersFieldBuilder() : null;
          } else {
            usersBuilder_.addAllMessages(other.users_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      main.java.io.grpc.chatservice.Channel parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (main.java.io.grpc.chatservice.Channel) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object channelName_ = "";
    /**
     * <code>optional string channelName = 1;</code>
     */
    public java.lang.String getChannelName() {
      java.lang.Object ref = channelName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channelName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string channelName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getChannelNameBytes() {
      java.lang.Object ref = channelName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string channelName = 1;</code>
     */
    public Builder setChannelName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      channelName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string channelName = 1;</code>
     */
    public Builder clearChannelName() {
      
      channelName_ = getDefaultInstance().getChannelName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string channelName = 1;</code>
     */
    public Builder setChannelNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      channelName_ = value;
      onChanged();
      return this;
    }

    private java.util.List<main.java.io.grpc.chatservice.User> users_ =
      java.util.Collections.emptyList();
    private void ensureUsersIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        users_ = new java.util.ArrayList<main.java.io.grpc.chatservice.User>(users_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        main.java.io.grpc.chatservice.User, main.java.io.grpc.chatservice.User.Builder, main.java.io.grpc.chatservice.UserOrBuilder> usersBuilder_;

    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public java.util.List<main.java.io.grpc.chatservice.User> getUsersList() {
      if (usersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(users_);
      } else {
        return usersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public int getUsersCount() {
      if (usersBuilder_ == null) {
        return users_.size();
      } else {
        return usersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public main.java.io.grpc.chatservice.User getUsers(int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);
      } else {
        return usersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public Builder setUsers(
        int index, main.java.io.grpc.chatservice.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.set(index, value);
        onChanged();
      } else {
        usersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public Builder setUsers(
        int index, main.java.io.grpc.chatservice.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.set(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public Builder addUsers(main.java.io.grpc.chatservice.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(value);
        onChanged();
      } else {
        usersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public Builder addUsers(
        int index, main.java.io.grpc.chatservice.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUsersIsMutable();
        users_.add(index, value);
        onChanged();
      } else {
        usersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public Builder addUsers(
        main.java.io.grpc.chatservice.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public Builder addUsers(
        int index, main.java.io.grpc.chatservice.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.add(index, builderForValue.build());
        onChanged();
      } else {
        usersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public Builder addAllUsers(
        java.lang.Iterable<? extends main.java.io.grpc.chatservice.User> values) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, users_);
        onChanged();
      } else {
        usersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public Builder clearUsers() {
      if (usersBuilder_ == null) {
        users_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        usersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public Builder removeUsers(int index) {
      if (usersBuilder_ == null) {
        ensureUsersIsMutable();
        users_.remove(index);
        onChanged();
      } else {
        usersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public main.java.io.grpc.chatservice.User.Builder getUsersBuilder(
        int index) {
      return getUsersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public main.java.io.grpc.chatservice.UserOrBuilder getUsersOrBuilder(
        int index) {
      if (usersBuilder_ == null) {
        return users_.get(index);  } else {
        return usersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public java.util.List<? extends main.java.io.grpc.chatservice.UserOrBuilder> 
         getUsersOrBuilderList() {
      if (usersBuilder_ != null) {
        return usersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(users_);
      }
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public main.java.io.grpc.chatservice.User.Builder addUsersBuilder() {
      return getUsersFieldBuilder().addBuilder(
          main.java.io.grpc.chatservice.User.getDefaultInstance());
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public main.java.io.grpc.chatservice.User.Builder addUsersBuilder(
        int index) {
      return getUsersFieldBuilder().addBuilder(
          index, main.java.io.grpc.chatservice.User.getDefaultInstance());
    }
    /**
     * <code>repeated .chatservice.User users = 2;</code>
     */
    public java.util.List<main.java.io.grpc.chatservice.User.Builder> 
         getUsersBuilderList() {
      return getUsersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        main.java.io.grpc.chatservice.User, main.java.io.grpc.chatservice.User.Builder, main.java.io.grpc.chatservice.UserOrBuilder> 
        getUsersFieldBuilder() {
      if (usersBuilder_ == null) {
        usersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            main.java.io.grpc.chatservice.User, main.java.io.grpc.chatservice.User.Builder, main.java.io.grpc.chatservice.UserOrBuilder>(
                users_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        users_ = null;
      }
      return usersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:chatservice.Channel)
  }

  // @@protoc_insertion_point(class_scope:chatservice.Channel)
  private static final main.java.io.grpc.chatservice.Channel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new main.java.io.grpc.chatservice.Channel();
  }

  public static main.java.io.grpc.chatservice.Channel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Channel>
      PARSER = new com.google.protobuf.AbstractParser<Channel>() {
    public Channel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      try {
        return new Channel(input, extensionRegistry);
      } catch (RuntimeException e) {
        if (e.getCause() instanceof
            com.google.protobuf.InvalidProtocolBufferException) {
          throw (com.google.protobuf.InvalidProtocolBufferException)
              e.getCause();
        }
        throw e;
      }
    }
  };

  public static com.google.protobuf.Parser<Channel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Channel> getParserForType() {
    return PARSER;
  }

  public main.java.io.grpc.chatservice.Channel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

