// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat_proto/chat.proto

package io.grpc.chatservice;

public final class ChatServiceProto {
  private ChatServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_chatservice_Message_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chatservice_Message_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_chatservice_User_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chatservice_User_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_chatservice_Channel_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_chatservice_Channel_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025chat_proto/chat.proto\022\013chatservice\">\n\007" +
      "Message\022\017\n\007channel\030\001 \001(\t\022\017\n\007message\030\002 \001(" +
      "\t\022\021\n\tclientKey\030\003 \001(\t\"\'\n\004User\022\021\n\tclientKe" +
      "y\030\001 \001(\t\022\014\n\004nick\030\002 \001(\t\"1\n\007Channel\022\023\n\013chan" +
      "nelName\030\001 \001(\t\022\021\n\tclientKey\030\002 \001(\t2\314\002\n\013Cha" +
      "tService\022.\n\004nick\022\021.chatservice.User\032\021.ch" +
      "atservice.User\"\000\0224\n\004join\022\024.chatservice.C" +
      "hannel\032\024.chatservice.Channel\"\000\0225\n\005leave\022" +
      "\024.chatservice.Channel\032\024.chatservice.Chan" +
      "nel\"\000\022.\n\004exit\022\021.chatservice.User\032\021.chats",
      "ervice.User\"\000\022:\n\013getMessages\022\021.chatservi" +
      "ce.User\032\024.chatservice.Message\"\0000\001\0224\n\004sen" +
      "d\022\024.chatservice.Message\032\024.chatservice.Me" +
      "ssage\"\000B)\n\023io.grpc.chatserviceB\020ChatServ" +
      "iceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_chatservice_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chatservice_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chatservice_Message_descriptor,
        new java.lang.String[] { "Channel", "Message", "ClientKey", });
    internal_static_chatservice_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chatservice_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chatservice_User_descriptor,
        new java.lang.String[] { "ClientKey", "Nick", });
    internal_static_chatservice_Channel_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chatservice_Channel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_chatservice_Channel_descriptor,
        new java.lang.String[] { "ChannelName", "ClientKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
