// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoExercise/chat_proto/chat.proto

package main.java.io.grpc.chatservice;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chatservice.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string clientKey = 1;</code>
   */
  java.lang.String getClientKey();
  /**
   * <code>optional string clientKey = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientKeyBytes();

  /**
   * <code>optional string nick = 2;</code>
   */
  java.lang.String getNick();
  /**
   * <code>optional string nick = 2;</code>
   */
  com.google.protobuf.ByteString
      getNickBytes();

  /**
   * <code>repeated .chatservice.Message messages = 3;</code>
   */
  java.util.List<main.java.io.grpc.chatservice.Message> 
      getMessagesList();
  /**
   * <code>repeated .chatservice.Message messages = 3;</code>
   */
  main.java.io.grpc.chatservice.Message getMessages(int index);
  /**
   * <code>repeated .chatservice.Message messages = 3;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .chatservice.Message messages = 3;</code>
   */
  java.util.List<? extends main.java.io.grpc.chatservice.MessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .chatservice.Message messages = 3;</code>
   */
  main.java.io.grpc.chatservice.MessageOrBuilder getMessagesOrBuilder(
      int index);

  /**
   * <code>repeated .chatservice.Channel channels = 4;</code>
   */
  java.util.List<main.java.io.grpc.chatservice.Channel> 
      getChannelsList();
  /**
   * <code>repeated .chatservice.Channel channels = 4;</code>
   */
  main.java.io.grpc.chatservice.Channel getChannels(int index);
  /**
   * <code>repeated .chatservice.Channel channels = 4;</code>
   */
  int getChannelsCount();
  /**
   * <code>repeated .chatservice.Channel channels = 4;</code>
   */
  java.util.List<? extends main.java.io.grpc.chatservice.ChannelOrBuilder> 
      getChannelsOrBuilderList();
  /**
   * <code>repeated .chatservice.Channel channels = 4;</code>
   */
  main.java.io.grpc.chatservice.ChannelOrBuilder getChannelsOrBuilder(
      int index);
}
